### ISSUE TITLE
Show more useful examples & chain actions

### ISSUE THREAD

**Issue by Akronae** [Makepad-fr/auto-release-on-version-bump#30]
Hi,

I think the sample shown to get started could be improved with something actually usable like so:

```yaml
name: Create a new release on `package.json#version` bump

on:
  push:
    branches:
      - main

jobs:
  release-on-version-bump:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: Makepad-fr/auto-release-on-version-bump-action@0.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "$newVersion"
          body: "✨ New release $newVersion"
          draft: "false"
          pre-release: "auto"
          generate-release-note: "true"
          tag-name: "$newVersion"
```
trigger, jobs and permission were missing, and the action name was wrong.

Last thing, do you know how to have some other action run when this action creates a new release?
I have another action of this sort
```yaml
name: Publish Package to yarn

on:
  release:
    types: [published]
```
But it does not get triggered when `auto-release-on-version-bump-action` creates a new release.

Thanks for your action its great!
